spring:
  application:
    name: paperless-rest
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/paperless}
    username: ${DB_USERNAME:paperless}
    password: ${DB_PASSWORD:paperless}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    open-in-view: false

server:
  port: 8081
